import Link from "next/link";
import { notFound } from "next/navigation";
import ReactMarkdown from "react-markdown";
import { getRun } from "@/lib/db";

const markdownComponents = {
  h2: (props: React.ComponentPropsWithoutRef<"h2">) => (
    <h2 className="mt-4 mb-1 text-base font-semibold first:mt-0" {...props} />
  ),
  ul: (props: React.ComponentPropsWithoutRef<"ul">) => (
    <ul className="my-2 list-disc space-y-1 pl-5" {...props} />
  ),
  strong: (props: React.ComponentPropsWithoutRef<"strong">) => (
    <strong className="font-semibold" {...props} />
  ),
  hr: () => <hr className="my-4 border-blue-200" />,
  p: (props: React.ComponentPropsWithoutRef<"p">) => (
    <p className="mb-2 last:mb-0" {...props} />
  ),
};

// Always read the live database - never serve a stale build-time snapshot.
export const dynamic = "force-dynamic";

function formatDateTime(epochSeconds: number): string {
  return new Date(epochSeconds * 1000).toLocaleString("en-GB", {
    dateStyle: "medium",
    timeStyle: "short",
  });
}

function platformLabel(source: string): string {
  if (source === "whatsapp") return "WhatsApp";
  if (source === "telegram") return "Telegram";
  return source;
}

export default async function RunPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const run = getRun(id);

  if (!run) {
    notFound();
  }

  return (
    <main className="mx-auto w-full max-w-3xl flex-1 px-6 py-10">
      <Link href="/" className="text-sm text-gray-500 hover:underline">
        ← All activity
      </Link>

      <div className="mt-4 flex items-start justify-between gap-4">
        <h1 className="text-xl font-semibold">
          {run.title ?? "Untitled listing"}
        </h1>
        <span
          className={
            "shrink-0 rounded-full px-2.5 py-1 text-xs font-medium " +
            (run.status === "completed"
              ? "bg-green-100 text-green-800"
              : "bg-amber-100 text-amber-800")
          }
        >
          {run.status === "completed" ? "Completed" : "In progress"}
        </span>
      </div>

      <p className="mt-1 text-sm text-gray-500">
        {formatDateTime(run.startedAt)} · {platformLabel(run.source)}
        {run.displayName ? ` · ${run.displayName}` : ""}
        {run.estimatedCostUsd != null
          ? ` · ~$${run.estimatedCostUsd.toFixed(3)}`
          : ""}
      </p>

      <div className="mt-8 space-y-4">
        {run.messages.map((message, i) => (
          <div
            key={i}
            className={
              "rounded-lg border p-4 " +
              (message.role === "user"
                ? "border-gray-200 bg-gray-50"
                : "border-blue-100 bg-blue-50")
            }
          >
            <p className="mb-2 text-xs font-medium uppercase tracking-wide text-gray-500">
              {message.role === "user" ? "Sent to agent" : "Generated by Hermes"}
            </p>
            {message.role === "assistant" ? (
              <div className="text-sm">
                <ReactMarkdown components={markdownComponents}>
                  {message.content}
                </ReactMarkdown>
              </div>
            ) : (
              <p className="whitespace-pre-wrap text-sm">{message.content}</p>
            )}
          </div>
        ))}
      </div>
    </main>
  );
}
